### ISSUE TITLE
Видалення айтему в багатолотовому тендері

### ISSUE THREAD

**Issue by 0lmer** [openprocurement/openprocurement.api#100]
1. Створюємо тендер з одним лотом, й декількома айтемами.
2. Редагуємо тендер, й видаляємо айтем. На ЦБД він відправляється у тілі тендера, але поле "relatedLot" вказуємо як null. У відповіді отримуємо цей айтем без "relatedLot", тут все ок.
3. Робимо GET-запит для перевірки - все коректно, видалений айтем без relatedLot.
4. Знов редагуємо тендер. Додаємо новий айтем. Але вже після цього патчу (видалений айтем передаємо БЕЗ relatedLot у запиті), у відповіді від ЦБД relatedLot  в ньому знов з'являється

**Comment by 0lmer** [comment]
1. Створюємо тендер з двома айтемами "Item 1" та "Item 2" (через draft - POST + PATCH, баг відтворюється й при звичайному створенні)
2. Видаляємо "Item 2".
3. Редагуємо тендер. Додаємо "Item 3". Одразу у відповіді з’являється "relatedLot" у видаленому раніше "Item 2"

https://gist.github.com/0lmer/ab023a5a467beb43f3a49e02abd8594a

**Comment by kroman0** [comment]
@0lmer items некоректно заміняється. Варіанти коректної поведінки:

1. додавати "Item 3" в кінець списку а не на початок
2. заміняти "Item 2" на "Item 3"
3. при додаванні "Item 3" в "Item 2" relatedLot записувати null
