### ISSUE TITLE
Зміни щодо об'єднаних контрактів при скасуванні аварда

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.api#118]
https://github.com/openprocurement/openprocurement.api/blob/merged_contracts/src/openprocurement/api/views/award.py#L324
@Krokop
https://github.com/openprocurement/openprocurement.api/pull/116#issuecomment-251609387

**Comment by Krokop** [comment]
@kroman0 це issue done, або ще щось упустив?

**Comment by kroman0** [comment]
так, done
