### ISSUE TITLE
Перевірки можливості підписати контракт по усіх об'єднаних авардах

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.api#119]
https://github.com/openprocurement/openprocurement.api/blob/merged_contracts/src/openprocurement/api/views/contract.py#L84
@Krokop 
https://github.com/openprocurement/openprocurement.api/pull/116#issuecomment-251609387

**Comment by Krokop** [comment]
Підписуватись будет тільки 1 контракт, тому я не дуже розумію навіщо ще якісь перевірки?

**Comment by kroman0** [comment]
Перевірка що контракт підписується після завершення всі періодів оскаржень і всі скарги розглянуті. Тобто не тільки по основному аварду а й по додаткових.
