### ISSUE TITLE
Зміни, пов'язані з контрактингом

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.api#135]
1) Гілка по розробці цих змін потребує оновлення згідно із останніми змінами в продуктиві
2) По тестах є велика дуплікація коду(наприклад, contract.py)

[simian.txt](https://github.com/openprocurement/openprocurement.api/files/619130/simian.txt)
[clonedigger.zip](https://github.com/openprocurement/openprocurement.api/files/619141/clonedigger.zip)

**Comment by kroman0** [comment]
@Krokop

**Comment by kroman0** [comment]
https://github.com/openprocurement/openprocurement.api/pull/139

**Comment by Krokop** [comment]
merged_contracts не будуть мержити в production ближчим часом?
