### ISSUE TITLE
Механізм "пришвидшених" тестових аукціонів

### ISSUE THREAD

**Issue by myroslav** [openprocurement/openprocurement.api#22]
@mazvv подав запит:
> mazvv: Я так понимаю, что изменить вручную дату и время аукциона в 0.6 не представляется возможным?
> myroslav: Яка мета є в зміні тих дат/годин аукціона? 
? mazvv: в целях тестирования
> myroslav: тобто в базі є Тендер і ви хочете якнайскорше по ньому провести аукціон?
> mazvv: так точно
> myroslav: без врахування механізму планування?
> mazvv: аукцион отдает запланированную дату/время а я хочу подвинуть вперед
> myroslav: "подвинуть вперед" - це скорше? ніж заплановано?
> mazvv: да

Було би добре на sandbox мати механізм "пришвидшення" часу, коли має відбутися аукціон, щоб не чекати наступного робочого дня.

**Comment by lerich** [comment]
Предлагаю поднять приоритер, так как реализация данного функционала является стопером для миграции на 06. Растягивать цикл тестирования на 2 дня - при нашем темпе не допустимо.

**Comment by kroman0** [comment]
@lerich @mazvv
Готово. Тепер якщо в полі `submissionMethodDetails` вказати слово `quick` то аукціон запланується протягом пів години після закінчення `tenderPeriod`.
