### ISSUE TITLE
Contact Point Error для email с новыми domains

### ISSUE THREAD

**Issue by mazvv** [openprocurement/openprocurement.api#24]
Есть проблема с постингом предложений, в ContactPoint которых присутствуют email с новыми доменными именами, например: info@rada.company

**Comment by myroslav** [comment]
13 днів тому в бібліотеці яка використовується для перевірки допустимих email адрес збільшили кількість допустимих символів в останньому сегменті з 6 до 10: https://github.com/schematics/schematics/commit/2f90a4ad399a0f4fe8a68d1ddd64ad00d63efb05. На production сервері ще діє обмеження в 6 символів. Нової версії бібліотеки ще не випускали.

Якщо ситуація критична, і не можна чекати нової версії бібліотеки, то можна буде спробувати перевипустити її в "робочому" варіанті, тільки з необхідною зміною. Тоді потрібно буде перезібрати систему на sandbox з новою бібліотекою, тоді відтестувати сумісність, і внести в графік викочування на production.

Звичайно краще це робити з версією біліотеки, яка випущена upstream, щоб не підтримувати свої patch-і.

**Comment by myroslav** [comment]
...віддав ще upstream issue: https://github.com/schematics/schematics/issues/299

**Comment by myroslav** [comment]
Проміжний fix є в https://github.com/schematics/schematics/commit/2b4812e5174f0b6891d5584850f89c73f0fc49aa, цю задачу будемо закривати після викладення fix-а на sandbox.

**Comment by darchik** [comment]
Мирослав, я думаю, что некритично сейчас бить тревогу конечно из-за этих адресов, но откладывать в ящик тоже не стоит.

**Comment by myroslav** [comment]
Зараз очікуємо випуск "свіжої" версії бібліотеки в першій декаді квітня, і в другій декаді ми б мали викласти fix на sandbox, і після тестування - на production.

**Comment by kroman0** [comment]
На продакшині вже викладено свіжу версію бібліотеки
