### ISSUE TITLE
the doc about document Type is not valid

### ISSUE THREAD

**Issue by serjshevchenko** [openprocurement/openprocurement.api#34]
In the description of Document entity, the section of documentType is not valide. In the doc there is a type "contractAnnexe" but in the source code, the validation expects to receive "contractAnnexes"
please fix the doc and standards by urls
http://standards.openprocurement.org/document_types/recommended/contract_en.json
http://standards.openprocurement.org/document_types/recommended/contract_uk.json
http://standards.openprocurement.org/document_types/recommended/contract_en.json

**Comment by kroman0** [comment]
Fixed by https://github.com/openprocurement/openprocurement.api/pull/46
