### ISSUE TITLE
api filters

### ISSUE THREAD

**Issue by rhyhro** [openprocurement/openprocurement.api#440]
@VDigitall, @chervol, @kroman0 
Using this url [https://public.api.openprocurement.org/api/2/tenders](url) I will get all tenders, but I want to get only completed tenders or tenders with specific classification. Do you have in api some filters as additional parameters for request, cause I didn't find information about it in documentation? I will appreciate if someone can help me.

**Comment by VDigitall** [comment]
API does not support filters, but you can include additional field `status` to response, query string will be looks like:
```https://public.api.openprocurement.org/api/2.4/tenders?opt_fields=status```
About specific classification you need still get each tender for check or look for third party services which provide this abilities.

**Comment by rhyhro** [comment]
@VDigitall thank you for response. I have one more question. In documentation in one example I have noticed, that you use some modes in request params `GET /api/2.3/tenders?mode=__all__ HTTP/1.0`
**Maybe you have another modes for accessing to specific tenders, for example by tender's status?** :)
I will appreciate for response
![prozorro_api](https://user-images.githubusercontent.com/49511783/61778876-45786400-ae08-11e9-837a-95eb9a36156b.png)

**Comment by VDigitall** [comment]
@Ruby4Ninja you are welcome.
Unfortunately `mode` accept only `__all__` or `test`, this mode allow to control which tenders will be displayed in response by default only productive tenders.

- `__all__` - include productive and test tenders

- `test` - include only test tenders
