### ISSUE TITLE
Чи оновлюється цей репозиторій?

### ISSUE THREAD

**Issue by drimacus182** [openprocurement/openprocurement.api#458]
З огляду на те, що останній коміт був 3 роки тому, хочу запитати, який статус цього репозиторію? Чи це правильне місце, де дивитись документацію по роботі із API Prozorro, чи можливо свіжа документація є в якомусь іншому місці?

**Comment by VDigitall** [comment]
Вітаю @drimacus182, для роботи з API Prozorro, Вам потрібно використувати репозиторій https://github.com/prozorroukr/openprocurement.api, в якому знайдете посилання на документацію.

**Comment by reinaldo2507** [comment]
English please

**Comment by VDigitall** [comment]
Hi @reinaldo2507, no, at the current time this repo doesn't have updates, for work with Prozorro API you need to follow instructions from this repo: https://github.com/prozorroukr/openprocurement.api, thanks for your interest.

**Comment by drimacus182** [comment]
Дякую
