### ISSUE TITLE
Testing out API

### ISSUE THREAD

**Issue by jakepruitt** [openprocurement/openprocurement.api#58]
Hello! Love the work that's going on here, and love the documentation you have in place. Would it be possible to document how to start the server? I was able to do the following:

```
python bootstrap.py
./bin/buildout -N
```

successfully, but I'm not sure what command to run next to start the server up.

Thank you!

**Comment by myroslav** [comment]
bin/circusd should bring all required processes up.

For API to start accepting data, you'd need extra auth.ini file with API
keys.

On Thursday, 4 February 2016, Jake Pruitt <notifications@github.com> wrote:

> Hello! Love the work that's going on here, and love the documentation you
> have in place. Would it be possible to document how to start the server? I
> was able to do the following:
>
> python bootstrap.py
> ./bin/buildout -N
>
> successfully, but I'm not sure what command to run next to start the
> server up.
>
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openprocurement/openprocurement.api/issues/58>.
>


-- 
....................................................................................................................................
Myroslav Opyr   ▪   CTO   ▪    Quintagroup   ▪   +1.917.475.4725   ▪
http://quintagroup.com
˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙

**Comment by selurvedu** [comment]
@myroslav, that's for https://github.com/openprocurement/openprocurement.buildout

**Comment by selurvedu** [comment]
`auth.ini` format:

```
[group_name]
user_name = api_key

[another_group_name]
another_user_name = another_api_key
```

For example:
```
[admins]
superuser = 26fda1ba49924ab29b91e14a7c22a586

[brokers]
bid.tenders.acme = 007db660944546b5b3a654dff274d229
```

You can give any names for users and groups, but only particular names will be effective. Here's a list (for ver. 0.12b2):
https://github.com/openprocurement/openprocurement.api/blob/0.12b2/src/openprocurement/api/traversal.py#L14-L32

We use 32-symbol UUIDs for API keys, but that is not a strict requirement too, e.g.: https://github.com/openprocurement/openprocurement.api/blob/0.12b2/src/openprocurement/api/tests/auth.ini

**Comment by myroslav** [comment]
@selurvedu thank you for comments.

This repository `buildout.cfg` is only for testing API package itself. 

Full dev-grade system can be built with [openprocurement/openprocurement.buildout](https://github.com/openprocurement/openprocurement.buildout) and our comments apply to software built that way.

**Comment by jakepruitt** [comment]
Thanks for the help! Got it up and running
