### ISSUE TITLE
Единицы измерения лота

### ISSUE THREAD

**Issue by darchik** [openprocurement/openprocurement.api#9]
Основываясь на том списке, что дал Мирослав, выбрал самое полезно-адекватное.

http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Abampere

К сожалению, не нашел такого понятия как ШТ! Возможно, вы найдете.

 *Список здесь*

https://www.evernote.com/shard/s54/sh/4591a1ac-ecb9-4b89-ae40-cca5d39cbb62/eaa3600f6e29828bf2030819088db045

**Comment by myroslav** [comment]
Перелік `Unit.code` які дозволені:
* http://standards.openprocurement.org/unit_codes/en.json
* http://standards.openprocurement.org/unit_codes/en_pretty.json
* http://standards.openprocurement.org/unit_codes/en.yaml
* http://standards.openprocurement.org/unit_codes/en_pretty.yaml

**Comment by lerich** [comment]
Добрый день. Вопрос по переводу справочников. Актуально для тестирования, так как не все заказчики на ты с английским...

**Comment by myroslav** [comment]
[Рекомендовані до використання одиниці виміру](http://opendata.org.ua/dataset/recommended-units-of-measure):
 * http://standards.openprocurement.org/unit_codes/recommended/uk.json
 * http://standards.openprocurement.org/unit_codes/recommended/en.json
 * http://standards.openprocurement.org/unit_codes/recommended/ru.json
